sudo: required
services:
- docker
language: node_js
node_js:
- '6'
notifications:
  slack: hr48:SvKuG55pxLTMA8jOhiUECDOH
after_success:
- bash deploy.sh
env:
  global:
  - secure: NonFjy0h5GxRrpX+561Y1xhc3rOK/HJeq2A3tQW1kjv5ja2ga+qrFi4WYIWjm2WcIV/ii0deZKfmE5rv5QoDcC1ktsN0w+n+fFmeRqSvKPnMw9LrbolFSFhqSEe30y3S7yWiROC/Gpy7TKXJNgKuv8vB1xLAFs/aHZEnwXeGnSFUmnfJXO0zQ7Zch6Cl2EDYnD63C4d5CiB9EymrH0qqXB+QH1rd0ardrx54G21/mq0fJYlWVCz3xz7HudRyeara3xg7FNjBvuhSRwOLpmqg4mDu2BfNhmgrcdcuJf9RMXRbm1rzf/E64x3fo+0/kuH9RcrvGHnOdGcYREJ9PMAt2GuZ1PyBL6ng7al/+kBu8rVrR5xHI5RlwURtio+ZkBg3EzU4n/qgWXlXnNuEl8Vda7xLXkUdAeffEwDJVuLdnSv9QXP8AMgLXR4bR9ZuweqlWv1gp4SM0iHJmB1XsW0n16WJcUyyJnbypKPoQKBFq9UsRxaX7OSmX4NBOpCNjFn+sx97Z7h/OIl0zHzwfoE0xJaAN07LbrSd3KcJ+MeeYtkIN7kCiQolPeRz2QmuOt8Dj9YG9ysDJVu+zqWRY29jS9riQgQeyib/pQ3VQZF+okwKhfher1m0/RbC6Lp9iLPEKwW1+4HKM6Jzst2l+619fW6wNmhLoTz9GISqOwzNOqw=
  - secure: g9E4Y3gSHmv+IetstJFZtIdhl2wEYpMjga9kGZxr4exCphza+1Ucwq5i/O8X1BF20t8lnL4p620TemAibgbqvBl6kxeUgrJSsDSReHjgxCQqac5nEDH0Bb9YvwS537Qx8dtA/Jx6kkpb4edKgOnITOAs0efTAydEwAjUwi3FBEFZPMIF8z05VLVkXrlgDSsMaqdnLE2HbBQFCP6T086yEYhxaebc9mSCm/zKj8evRjpuQdlexzQU4KKzksgkM8mNp15HhPxCEnPZo/+mV3C4R8y5Tn9P2hjNh0TW1JwGtEVrLvyMzilDzLML7tk6D6GPmNnKLYohUVCq23ItQyVZZvPmDfPjPxHskgAeOCmaptmHwqeKqWGkZZssUKNZ8oXqDnbgMbrpdbwYvivYKl4uKLDjTu2HO0EIlcXXBx7AQZ2WsHV4RUBWVatAK6lJeT9Fpd1PaUH3KueOB/tHnoLyLLxQvnh7Wy2c7p6a4j8MWzZNCvm+RbYmDfo/E7NrCVQ6btRL+NN2OXXUPyun4cSwPD7e+QcOMttP2/IG1uLoRhJE2SQahaTx4Y6BSWtq+J8gux81biPdWBWlTKMC2wxjHiEVcaQ6pqpEiHqN9/+Vn1eqZU7/kc3uGMRrrg+ueMfV8V5OxHg+d8iA2fWPd1VLw4werHeWEKXGOhy0V+3t2Kg=
